function createkymo(xdata1, ydata1, zdata1)
%CREATEFIGURE(XDATA1, YDATA1, ZDATA1)
%  XDATA1:  contour x
%  YDATA1:  contour y
%  ZDATA1:  contour z

%  Auto-generated by MATLAB on 15-Aug-2014 15:52:52

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'YDir','reverse',...
    'XTickLabel',{'Head','mid','Tail'},...
    'XTick',[1 10 20],...
    'Position',[0.13 0.11 0.171033591731266 0.815],...
    'Layer','top',...
    'CLim',[-40 40]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[1 10]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.0666666666666667 24.9333333333333]);
box(axes1,'on');
hold(axes1,'all');

% Create contour
contour(xdata1,ydata1,zdata1,'LineStyle','none','LineColor',[0 0 0],...
    'LevelStep',2,...
    'Fill','on',...
    'Parent',axes1);
colormap jet
% Create xlabel
xlabel('Body Segment');

% Create ylabel
ylabel('Seconds');

% Create colorbar
colorbar('peer',axes1);
% Resize the axes in order to prevent it from shrinking.
set(axes1,'Position',[0.13 0.11 0.171033591731266 0.815]);

